# Generated by Django 5.2 on 2025-04-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started')], default='Not Started', max_length=20),
        ),
    ]
